apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "419"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"web","namespace":"staging"},"spec":{"replicas":1,"revisionHistoryLimit":1,"selector":{"matchLabels":{"app":"web","tier":"web"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":0},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"web","tier":"web"}},"spec":{"affinity":{"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"podAffinityTerm":{"labelSelector":{"matchExpressions":[{"key":"app","operator":"In","values":["web"]},{"key":"tier","operator":"In","values":["web"]}]},"topologyKey":"failure-domain.beta.kubernetes.io/zone"},"weight":1}]}},"containers":[{"env":[{"name":"DD_AGENT_HOST","valueFrom":{"fieldRef":{"fieldPath":"status.hostIP"}}},{"name":"DD_ENV","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"DD_SERVICE","valueFrom":{"fieldRef":{"fieldPath":"metadata.labels['app']"}}},{"name":"SECRET_KEY_BASE","valueFrom":{"secretKeyRef":{"key":"secret_key_base","name":"web"}}},{"name":"JWT_SECRET_KEY","valueFrom":{"secretKeyRef":{"key":"jwt_secret_key","name":"web"}}},{"name":"AUTH0_CLIENT_SECRET","valueFrom":{"secretKeyRef":{"key":"auth0_client_secret","name":"web"}}},{"name":"DB_PASSWORD","valueFrom":{"secretKeyRef":{"key":"db_password","name":"web"}}},{"name":"MONGODB_PASSWORD","valueFrom":{"secretKeyRef":{"key":"mongodb_password","name":"web"}}},{"name":"SMTP_PASSWORD","valueFrom":{"secretKeyRef":{"key":"smtp_password","name":"web"}}},{"name":"AWS_ACCESS_KEY_ID","valueFrom":{"secretKeyRef":{"key":"aws_access_key_id","name":"web"}}},{"name":"AWS_SECRET_KEY","valueFrom":{"secretKeyRef":{"key":"aws_secret_key","name":"web"}}},{"name":"GOOGLE_API_KEY","valueFrom":{"secretKeyRef":{"key":"google_api_key","name":"web"}}},{"name":"AERIALINK_SECRET","valueFrom":{"secretKeyRef":{"key":"aerialink_secret","name":"web"}}},{"name":"BRANCH_LIVE_SECRET","valueFrom":{"secretKeyRef":{"key":"branch_live_secret","name":"web"}}},{"name":"CUSTOM_TRUCK_ONE_API_SECRET_TOKEN","valueFrom":{"secretKeyRef":{"key":"custom_truck_one_api_secret_token","name":"web"}}},{"name":"RESMAN_API_KEY","valueFrom":{"secretKeyRef":{"key":"resman_api_key","name":"web"}}},{"name":"CHARGIFY_KEY","valueFrom":{"secretKeyRef":{"key":"chargify_key","name":"web"}}}],"envFrom":[{"configMapRef":{"name":"web"}}],"image":"r360/web:g0381ba22","name":"web","ports":[{"containerPort":80,"name":"web"}],"readinessProbe":{"failureThreshold":5,"httpGet":{"path":"/_status","port":"web"},"initialDelaySeconds":5,"periodSeconds":10,"timeoutSeconds":10},"resources":{"requests":{"cpu":0.5,"memory":"1Gi"}},"volumeMounts":[{"mountPath":"/app/config/secrets","name":"secrets","readOnly":true}]}],"imagePullSecrets":[{"name":"docker-hub"}],"volumes":[{"name":"secrets","secret":{"items":[{"key":"pspdfkit_key","path":"pspdfkit.pem"}],"secretName":"web"}}]}}}}
  creationTimestamp: "2020-12-07T19:38:03Z"
  generation: 430
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"web"}:
                f:env:
                  k:{"name":"JWT_SECRET_KEY"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"LOG_LEVEL"}:
                    .: {}
                    f:name: {}
                    f:value: {}
    manager: kubectl-edit
    operation: Update
    time: "2021-07-15T20:47:44Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:template:
          f:metadata:
            f:annotations:
              .: {}
              f:kubectl.kubernetes.io/restartedAt: {}
    manager: kubectl
    operation: Update
    time: "2021-08-19T18:46:50Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector:
          f:matchLabels:
            .: {}
            f:app: {}
            f:tier: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:app: {}
              f:tier: {}
          f:spec:
            f:affinity:
              .: {}
              f:podAntiAffinity:
                .: {}
                f:preferredDuringSchedulingIgnoredDuringExecution: {}
            f:containers:
              k:{"name":"web"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"AERIALINK_SECRET"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"AUTH0_CLIENT_SECRET"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"AWS_ACCESS_KEY_ID"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"AWS_SECRET_KEY"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"BRANCH_LIVE_SECRET"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"CHARGIFY_KEY"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"CUSTOM_TRUCK_ONE_API_SECRET_TOKEN"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"DB_PASSWORD"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"DD_AGENT_HOST"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:fieldRef:
                        .: {}
                        f:apiVersion: {}
                        f:fieldPath: {}
                  k:{"name":"DD_ENV"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:fieldRef:
                        .: {}
                        f:apiVersion: {}
                        f:fieldPath: {}
                  k:{"name":"DD_SERVICE"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:fieldRef:
                        .: {}
                        f:apiVersion: {}
                        f:fieldPath: {}
                  k:{"name":"GOOGLE_API_KEY"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"MONGODB_PASSWORD"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"RESMAN_API_KEY"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"SECRET_KEY_BASE"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"SMTP_PASSWORD"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                f:envFrom: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":80,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                f:readinessProbe:
                  .: {}
                  f:failureThreshold: {}
                  f:httpGet:
                    .: {}
                    f:path: {}
                    f:port: {}
                    f:scheme: {}
                  f:initialDelaySeconds: {}
                  f:periodSeconds: {}
                  f:successThreshold: {}
                  f:timeoutSeconds: {}
                f:resources:
                  .: {}
                  f:requests:
                    .: {}
                    f:cpu: {}
                    f:memory: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
                f:volumeMounts:
                  .: {}
                  k:{"mountPath":"/app/config/secrets"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                    f:readOnly: {}
            f:dnsPolicy: {}
            f:imagePullSecrets:
              .: {}
              k:{"name":"docker-hub"}:
                .: {}
                f:name: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
            f:volumes:
              .: {}
              k:{"name":"secrets"}:
                .: {}
                f:name: {}
                f:secret:
                  .: {}
                  f:defaultMode: {}
                  f:items: {}
                  f:secretName: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-09-27T23:27:44Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-09-28T00:57:27Z"
  name: web
  namespace: staging
  resourceVersion: "84295979"
  selfLink: /apis/apps/v1/namespaces/staging/deployments/web
  uid: a63ceb62-62a9-439d-8b75-8daec1530d33
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: web
      tier: web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2021-09-22T17:17:32-07:00"
      creationTimestamp: null
      labels:
        app: web
        tier: web
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - web
                - key: tier
                  operator: In
                  values:
                  - web
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 1
      containers:
      - env:
        - name: LOG_LEVEL
          value: DEBUG
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: DD_ENV
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: DD_SERVICE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app']
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              key: secret_key_base
              name: web
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: jwt_secret_key
              name: web
        - name: AUTH0_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: auth0_client_secret
              name: web
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: db_password
              name: web
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mongodb_password
              name: web
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: smtp_password
              name: web
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: aws_access_key_id
              name: web
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: aws_secret_key
              name: web
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              key: google_api_key
              name: web
        - name: AERIALINK_SECRET
          valueFrom:
            secretKeyRef:
              key: aerialink_secret
              name: web
        - name: BRANCH_LIVE_SECRET
          valueFrom:
            secretKeyRef:
              key: branch_live_secret
              name: web
        - name: CUSTOM_TRUCK_ONE_API_SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              key: custom_truck_one_api_secret_token
              name: web
        - name: RESMAN_API_KEY
          valueFrom:
            secretKeyRef:
              key: resman_api_key
              name: web
        - name: CHARGIFY_KEY
          valueFrom:
            secretKeyRef:
              key: chargify_key
              name: web
        envFrom:
        - configMapRef:
            name: web
        image: r360/web:g0381ba22
        imagePullPolicy: IfNotPresent
        name: web
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /_status
            port: web
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/config/secrets
          name: secrets
          readOnly: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: docker-hub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: secrets
        secret:
          defaultMode: 420
          items:
          - key: pspdfkit_key
            path: pspdfkit.pem
          secretName: web
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-08-02T23:47:15Z"
    lastUpdateTime: "2021-08-02T23:47:15Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-09-20T16:48:32Z"
    lastUpdateTime: "2021-09-28T00:57:27Z"
    message: ReplicaSet "web-6b8f6b9766" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 430
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
